services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Remind\Extbase\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Remind\Extbase\Service\DataService:
    shared: false
