services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Remind\Extbase\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Remind\Extbase\Service\ControllerService:
    shared: false
  Remind\Extbase\Controller\CustomValueEditorController:
    tags: ['backend.controller']
  Remind\Extbase\Event\Listener\SiteConfigurationLoaded:
    tags:
      - name: event.listener
