name: CI

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
      with:
        php_version: 8.1
        php_extensions: intl
        args: --no-scripts --ignore-platform-reqs
    - run: composer run-script phpcs
